apiVersion: apps/v1
kind: Deployment
metadata:
  name: LAMP-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: LAMP
  template:
    metadata:
      labels:
        app: LAMP
    spec:
      containers:
      - name: apache
        image: php:7.4-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: LAMP-volume
          mountPath: /var/www/html
      volumes:
      - name: LAMP-volume
        configMap:
          name: LAMP-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: LAMP-config
data:
  index.php: |
    <?php
    include 'config.php';

    $conn = new mysqli($servername, $username, $password, $dbname);

    if ($conn->connect_error) {
      die("Connection failed: " . $conn->connect_error);
    }

    $sql = "SELECT id, name FROM users";
    $result = $conn->query($sql);
    ?>

    <!DOCTYPE html>
    <html>
    <head>
        <title>LAMP</title>
        <link rel="stylesheet" type="text/css" href="css/styles.css">
    </head>
    <body>
        <h1>User List</h1>
        <table>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
            <?php
            if ($result->num_rows > 0) {
                while($row = $result->fetch_assoc()) {
                    echo "<tr><td>" . $row["id"]. "</td><td><a href='user.php?id=" . $row["id"]. "'>" . $row["name"]. "</a></td></tr>";
                }
            } else {
                echo "<tr><td colspan='2'>0 results</td></tr>";
            }
            $conn->close();
            ?>
        </table>
    </body>
    </html>
  config.php: |
    <?php
    $servername = "mysql-service";
    $username = "root";
    $password = "your_password";
    $dbname = "your_database";
    ?>
  user.php: |
    <?php
    include 'config.php';

    $conn = new mysqli($servername, $username, $password, $dbname);

    if ($conn->connect_error) {
      die("Connection failed: " . $conn->connect_error);
    }

    $id = intval($_GET['id']);
    $sql = "SELECT id, name FROM users WHERE id = $id";
    $result = $conn->query($sql);
    $row = $result->fetch_assoc();
    ?>

    <!DOCTYPE html>
    <html>
    <head>
        <title>User Details</title>
        <link rel="stylesheet" type="text/css" href="css/styles.css">
    </head>
    <body>
        <h1>User Details</h1>
        <?php if ($row): ?>
            <p>ID: <?php echo $row["id"]; ?></p>
            <p>Name: <?php echo $row["name"]; ?></p>
        <?php else: ?>
            <p>User not found.</p>
        <?php endif; ?>
        <a href="index.php">Back to User List</a>
    </body>
    </html>

    <?php
    $conn->close();
    ?>
  css/styles.css: |
    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        margin: 0;
        padding: 20px;
    }

    h1 {
        color: #333;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    table, th, td {
        border: 1px solid #ccc;
    }

    th, td {
        padding: 10px;
        text-align: left;
    }

    th {
        background-color: #eee;
    }

    a {
        color: #007BFF;
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }

    p {
        color: #333;
    }
---
apiVersion: v1
kind: Service
metadata:
  name: LAMP-service
spec:
  selector:
    app: LAMP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: LAMP-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
